### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by roaldarbol** [jasonjfoster/roll#46]
Hi again @jasonjfoster!
Could you consider writing some more documentation for the package? Currently, I need to go into `NAMESPACE` to figure out which functions are available in *roll* which is a pity since there are so many great functions. Maybe you could consider a simple pkgdown site which makes all the function documentation more discoverable?

**Comment by jasonjfoster** [comment]
You can refer to the manual on CRAN (https://cran.r-project.org/package=roll) or on r-universe (https://jasonjfoster.r-universe.dev/roll). Specifically the help manual page (https://jasonjfoster.r-universe.dev/roll/doc/manual.html) contains all the functions on a single page. Will add a link on GitHub for future users.

**Comment by roaldarbol** [comment]
That's perfect, thanks for pointing to it. Would indeed be great with a link from the README too.
